@bearerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJzdWIiOjEsIm5hbWUiOiJFbG1vX0JvcmVyIiwiaWF0IjoxNjg5MzY1MjIxLCJleHAiOjE2ODkzNjUyODF9.MehLAoJocpOk4wf6rRbImU6jphM1EcPH6CscObyEVBs
@port = 3333


### GET Testimonials

GET http://localhost:{{port}}/api/testimonials

### Create a new Testimonial

POST http://localhost:{{port}}/api/testimonials HTTP/1.1
Authorization: Bearer {{bearerToken}}
content-type: application/json

{
    "comment": "Alekinho88 es el mejor jugador de la historia del fútbol."
}


### SignIn
POST http://localhost:{{port}}/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "test@test.com",
    "password": "12345678Oi"
}

### Get logged user
GET http://localhost:{{port}}/api/auth/me
Authorization: Bearer {{bearerToken}}

### Delete
DELETE http://localhost:{{port}}/api/testimonials/6
Authorization: Bearer {{bearerToken}}