@bearerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJzdWIiOjEsIm5hbWUiOiJFbG1vX0JvcmVyIiwiaWF0IjoxNjg5MzY1MjIxLCJleHAiOjE2ODkzNjUyODF9.MehLAoJocpOk4wf6rRbImU6jphM1EcPH6CscObyEVBs


### GET Testimonials

GET http://localhost:3333/api/testimonials

### Create a new Testimonial

POST http://localhost:3333/api/testimonials HTTP/1.1
content-type: application/json

{
    "comment": "Alekinho88 es el mejor jugador de la historia del fútbol.",
    "user_id": 1
}


### SignIn
POST http://localhost:3333/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "test@test.com",
    "password": "12345678Oi"
}

### Get logged user
GET http://localhost:3333/api/auth/me
Authorization: Bearer {{bearerToken}}

### Delete
DELETE http://localhost:3333/api/testimonials/27