@bearerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiRGFycmVsX0xhcnNvbi1XaW5kbGVyIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNjg4ODk1MjA2LCJleHAiOjE2ODg5ODE2MDZ9.a24KBdMGTVci7Y8PVcnK1QzO6VonCLrP6kb5Nb3TeTA


### GET Testimonials

GET http://localhost:3333/api/testimonials

### Create a new Testimonial

POST http://localhost:3333/api/testimonials HTTP/1.1
content-type: application/json

{
    "name": "Alekinho 88",
    "content": "Alekinho88 es el mejor jugador de la historia del fútbol."
}


### SignIn
POST http://localhost:3333/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "test@test.com",
    "password": "12345678Oi"
}

### Get logged user
GET http://localhost:3333/api/auth/me
Authorization: Bearer {{bearerToken}}
